

     </main>
     <footer class="bg-secondary p-3 mt-5 text-center">
          Jeux olympiques
          <?php 
          unset($_SESSION['success']);
          unset($_SESSION['warning']);
          ?>
     </footer>

     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

     <script src="utils/js/script.js"></script>

</body>
</html>